// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY6Qp0u-2y4gsBdKpUrYsQT1Y5qcgb7KM',
    appId: '1:817472392896:web:8c845a7abc35cede9a6725',
    messagingSenderId: '817472392896',
    projectId: 'blackcoffertask-4c3eb',
    authDomain: 'blackcoffertask-4c3eb.firebaseapp.com',
    storageBucket: 'blackcoffertask-4c3eb.appspot.com',
    measurementId: 'G-YT4Z266HJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKF0wd1KtM679FnmjcEv9Iwca4Ma-3kxA',
    appId: '1:817472392896:android:3c3065c15a6029599a6725',
    messagingSenderId: '817472392896',
    projectId: 'blackcoffertask-4c3eb',
    storageBucket: 'blackcoffertask-4c3eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGYVIAsEgTmncN81GfNAuDMvWnl-bLPZw',
    appId: '1:817472392896:ios:9dfa890072ebe3f09a6725',
    messagingSenderId: '817472392896',
    projectId: 'blackcoffertask-4c3eb',
    storageBucket: 'blackcoffertask-4c3eb.appspot.com',
    iosBundleId: 'com.example.backcofferTask',
  );
}
